[phases.setup]
aptPkgs = ["wget", "ca-certificates", "fonts-liberation", "libatk-bridge2.0-0", "libatk1.0-0", "libcups2", "libdbus-1-3", "libgdk-pixbuf2.0-0", "libnspr4", "libnss3", "libx11-xcb1", "libxcomposite1", "libxdamage1", "libxrandr2", "libxfixes3", "xdg-utils", "libgbm1", "libxshmfence1"]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "node index.js"
