[phases.setup]
aptPkgs = ["chromium"]

[phases.install]
cmds = ["npm ci --include=optional"]

[start]
cmd = "PUPPETEER_SKIP_DOWNLOAD=true PUPPETEER_EXECUTABLE_PATH=$(which chromium || which chromium-browser || echo '/usr/bin/chromium') node index.js"
